### ISSUE TITLE
Link relevant content

### ISSUE THREAD

**Issue by bfung** [gfung/gfung.github.io#1]
Personal webpage on github should include:
- Resume or link to resume
- github profile, http://github.com/gfung, should link to http://gfung.github.io (see http://github.com/bfung for example)
- Link to LinkedIn profile
- Links to various other website accounts, such as StackOverflow, Code Academy, etc.

**Comment by bfung** [comment]
Bullet #2 isn't setup.  If I'm on http://gfung.github.io and click the github profile link, there's no way to get back on screen (back button works, but no obvious way to get back)

**Comment by gfung** [comment]
=\ thats a github profile thing. also updated.
