### ISSUE TITLE
LinkedIn Resume link doesn't work

### ISSUE THREAD

**Issue by bfung** [gfung/gfung.github.io#3]
I click the Resume link and see this (you do not have permissions to view this Resume):
![screen shot 2016-02-22 at 8 50 20 pm](https://cloud.githubusercontent.com/assets/240824/13242072/fbad6300-d9a5-11e5-9ae3-67e13cb14d6f.png)

**Comment by gfung** [comment]
Fixed. was a permissions issue from the linkedin side of things
